version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: jobportal-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_portal_db
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - jobportal-network
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: jobportal-app
    ports:
      - "8081:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/job_portal_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - jobportal-network

volumes:
  mysql_data:

networks:
  jobportal-network:
    driver: bridge